
#server:
#  port: ${PORT:${SERVER_PORT:0}}  # Deja que Spring asigne un puerto aleatorio si no se especifica
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_almacen
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /doc/swagger-ui.html
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


server:
  #  port: 8091
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: ms-almacen-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_almacen?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka
#  instance:
#    hostname: localhost
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
